baseURL = "//mitchellkember.com/blog/"
languageCode = "en-us"
title = "Mitchell Kember"
pygmentsStyle = "friendly"

[taxonomies]
category = "categories"

[params]
author = "Mitchell Kember"
homepage = "https://mitchellkember.com"

[markup.goldmark.renderer]
# Required for some HTML embedding, e.g. the verse.html shortcode.
unsafe = true
